#!/bin/bash

function commands() {
    echo -e "\nOptions:"
    echo -e "\033[1;32m-h, --help\033[0;39m              display help for command\n"

    echo -e "Commands:"
    echo -e " \033[1;32msandbox\033[0;39m                open project"
    echo -e " \033[1;32msandbox init\033[0;39m           initial setup"
    echo -e " \033[1;32msandbox update\033[0;39m         update settings"
    echo -e " \033[1;32msandbox open\033[0;39m           open project"
    echo -e " \033[1;32msandbox info\033[0;39m           check settings"
    echo -e " \033[1;32msandbox reset\033[0;39m          reset settings"
    echo -e " \033[1;32msandbox upgrade\033[0;39m        update the main unit"
    echo -e " \033[1;32msandbox uninstall\033[0;39m      delete the main unit\n"
}
