#!/bin/bash

function er_init() {
    read -p "Do you want to do the initial setup? [Y/n]: " answer
    case $answer in
        "" | "Y" | "y" | "yes" | "Yes" | "YES" ) ;;
        * ) mg_init;;
    esac
    init
    exit 1
}
