#!/bin/bash

function info() {
    if [ ! -e ./sandbox.conf ]; then
        mg_init; er_init;
    fi

    source ./sandbox.conf

    if [ -n "$created" ]; then
        echo -e "created: \033[1;32m$created\033[0;39m"
    fi
    if [ -n "$updated" ]; then
        echo -e "updated: \033[1;32m$updated\033[0;39m"
    fi
    echo -e "project_dir: \033[1;32m$dir\033[0;39m"
}
