#!/bin/bash

function init() {
    if [ -e ./sandbox.conf ]; then
        mg_reset
        exit 1
    fi
    read -p "Project Directory: " dir
    expanded_dir="${dir/#\~/$HOME}"
    if [ ! -e "$expanded_dir" ]; then
        mkdir -p "$expanded_dir"
        echo -e "Created directory \033[1;32m$dir\033[0;39m."
    else
        echo -e "The \033[1;32m$dir\033[0;39m already exists."
    fi
    echo "created='$(date -Iseconds)'" > ./sandbox.conf
    echo "dir='${dir}'" >> ./sandbox.conf
    echo -e "\033[1;34mInitial setup is complete.\033[0;39m"
}
