#!/bin/bash

function open() {
    if [ ! -e ./sandbox.conf ]; then
        mg_init; er_init;
    fi
    source ./sandbox.conf
    expanded_dir="${dir/#\~/$HOME}"
    cd "$expanded_dir"
    
    folders=($(find . -maxdepth 1 -type d | sort | sed '1d; s|^\./||'))

    if [ ${#folders[@]} -eq 0 ]; then
        error "Project does not exist."
    fi

    if [ -n "$1" ] && [[ "$1" =~ ^[0-9]+$ ]]; then
        choice=$1
    else
        echo "Please select a project:"
        for i in "${!folders[@]}"; do
            echo " $((i+1))) ${folders[i]}"
        done

        read -p "Enter a number: " choice
    fi

    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le "${#folders[@]}" ]; then
        selected_folder="${folders[$((choice-1))]}"
        
        code "$selected_folder"
        echo -e "\033[1;32mProject $selected_folder is opened in Visual Studio Code.\033[0;39m"
    else
        error "Invalid choice."
    fi
}
