#!/bin/bash

function reset() {
    if [ ! -e ./sandbox.conf ]; then
        mg_init; er_init;
    fi
    read -p "Do you want to reset settings? [Y/n]: " answer
    case $answer in
        "" | "Y" | "y" | "yes" | "Yes" | "YES" ) ;;
        * ) exit 1;;
    esac
    rm -f ./sandbox.conf
    echo -e "\033[1;34mReset is complete.\033[0;39m"
}
